# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df62e50f42b6f482dfbdaf387180a9968fd2118b50960a276b5db8b4692ef3cc6c19be7927ec0a62aa34c8b2f2443ddcaaf9db685d657bec1ab7d49dd76e21f

test:
  secret_key_base: f1653684f7f7f3048c8a29f17a55192fb5db716feabd735ad4c35efcc9eb6606dcdadf888df9939c4b339feb8c4022f2715ab04f5a722de0da290524112b8f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
